/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
//    id("buildlogic.java-application-conventions")// test remove
    id("buildlogic.java-common-conventions")// replace 1 line up
    // I added -
    id("org.springframework.boot") version "3.2.0"
    id("io.spring.dependency-management") version "1.1.4"
    java
    //-
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    // I added -
    implementation(project(":list"))
    implementation(project(":utilities"))

    implementation("org.springframework.boot:spring-boot-starter-web")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    //-
}

/*application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}*/
// I added -
tasks.test {
    useJUnitPlatform()
}
//-
